#!/bin/bash

set -e errexit #exit the shell if execution result is wrong


THIS_DIR=$(cd $(dirname $0);pwd)
THIS_FILE=$(basename $0)


wget https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-latest-$(uname -s)-$(uname -m).sh
bash $THIS_DIR/Miniconda3-latest-$(uname -s)-$(uname -m).sh
#需要重启一次终端？
#不修改配置miniconda3的地址
source miniconda3/bin/activate



#解决在shell脚本中切换conda的问题https://www.jianshu.com/p/bc1efaf5997c
condaenv="$(conda info | grep -i 'base environment')"
source $condaenv/etc/profile.d/conda.sh
conda activate envname
conda info --envs





exit 0

